### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by ryonakano**
## Changes Summary
- Use `Gtk.Application` instead of `Granite.Application` ([deprecated since 0.5.0](https://github.com/elementary/granite/blob/3c25b6c95e5ddf3fcc3bdf8bf1014f6d2246e677/lib/Application.vala#L25))
- Use `GLib.Settings` instead of `Granite.Services.Settings` ([deprecated since 5.3.2](https://github.com/elementary/granite/blob/d1a3b97c7a5842bf3f757d41d9816b3d4e50d3e9/lib/Services/Settings.vala#L94))
- Use `Gtk.Application.set_accels_for_action` instead of `Gtk.Application.add_accelerator` ([deprecated since 3.14](https://valadoc.org/gtk+-3.0/Gtk.Application.add_accelerator.html))

### CODE REVIEW

**Comment by bcedu** [comment]
Hi! Thanks for contributing. I've tried to build the app with your changes and I get an error when processing the `post_install.py`

Captura de pantalla del 2020-04-09 18 21 53

**Comment by ryonakano** [comment]
Screenshot from 2020-04-10 14-21-22

Hmm, I don't see that error… :thinking:

**Comment by ryonakano** [comment]
@bcedu I don't add any changes to post_install.py or GSchemas files, so I don't think that error is because of this PR.

**Comment by ryonakano** [comment]
@bcedu Any chance you take another look at this?

**Pull request closed without merging**
