### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon was really not compliant by [eOS HIG](https://elementary.io/docs/human-interface-guidelines#iconography). It was the wrong size, not a vector (it's svg, doesn't mean its scalable). Not even skeuomorphic like how eOS Icon should be.

### CODE REVIEW

**Comment by bcedu** [comment]
Can you make it with the same colors than the original one? 🙏🏻

**Comment by Fatih20** [comment]
I didn't make it with the original one because as outlined in James Blaede [palette app](https://appcenter.elementary.io/com.github.cassidyjames.palette/), purple should be used for networking related app.

**Comment by bcedu** [comment]
And something that combines blue (for "downloading") and purple (for "network" and "share"). Also i liked the icon of the computer for the logo because it is identified as a "server" (maybe it should be more minimalist tha the one i made, of course)

**Comment by Fatih20** [comment]
I think I have an idea. I'll get on it.

**Pull request merged**
