### PR TITLE
Render update

### PR DESCRIPTION
**Pull request by amka**
WIP: Replace default HTML styles

Plans to be done: 
- [x] responsive layout
- [x] sticky header
- [x] add type icons
- [x] display file size
- [x] display file type
- [x] modifications date
- [x] sort by type and alphabet
- [x] don't display hidden files

https://user-images.githubusercontent.com/519146/147421628-f0fc5d54-4f19-4309-9f34-70449497d64d.mp4

### CODE REVIEW

**Comment by amka** [comment]
@bcedu feel free to point me in the direction you're curious about if you disagree with something I wrote.

**Comment by amka** [comment]
New icons (https://github.com/icons8/flat-color-icons) and updated colors

https://user-images.githubusercontent.com/519146/147539931-4609c876-6567-4b64-a62b-ef002bdd7d18.mp4

**Comment by bcedu** [comment]
it looks awesome!

**Comment by amka** [comment]
## New
- modification datetime
- hidden files are hidden
- folders and files sorted alphabetically
- folders first, files second
- and more file types

https://user-images.githubusercontent.com/519146/147615246-fbbb658c-8860-4b95-9c37-37ed377c9550.mp4

**Comment by amka** [comment]
I decided to postpone my efforts of making a preview page for audio/video/images until I realize a better way of handling a bunch of assets.

@bcedu PR is ready.

**Comment by bcedu** [comment]
Nice! I will review and test it this weekend. Thanks for all the work!

**Review by bcedu — APPROVED** [review]

**Pull request merged**
