### PR TITLE
Replace libsoup with 3.0

### PR DESCRIPTION
**Pull request by amka**
## Changes:
- Replaced libsoup with 3.0 version
- Add module to Flatpak-manifest

### CODE REVIEW

**Comment by bcedu** [comment]
Hi! Thanks for the PR. Just a one question, I want to test i but I don't know how to isntall the package libsoup-3.0. Did you installed from `apt`?

**Comment by bcedu** [comment]
Well, I see from the changes in the `com.github.bcedu.valasimplehttpserver.yml` that you use the release published on gitlab. I dind't found the 3.0 published in any package throught apt so I supose this is the way to use it.

**Comment by amka** [comment]
> Hi! Thanks for the PR. Just a one question, I want to test i but I don't know how to isntall the package libsoup-3.0. Did you installed from `apt`?

@bcedu well, actually I went to sleep before I tested it :) Probably the good idea is to install it from sources and place this step into `actions`.

**Comment by bcedu** [comment]
I made a commit to:

- Update tests with the new changes
- Fix `normalize_path` using `Glib.Uri.escape_string`
- Add compatibility with libsoup 2.0


As you can see, I made some changes in order to be able to work with both: libsoup 2.0 and 3.0. I made this because I've seen that libsoup3.0 is only aviable in the last releases of Ubuntu and Debian, but the current Ubuntu LTS doesn' have libsoup3.0 and can not be installed because it requires glib>=2.69.1, which is not aviable in older releases.

As I want to make this app aviable for all Debian based distros without having to use flatpak, I made the use of libsoup3.0 optional.

**Review by bcedu — APPROVED** [review]

**Comment by amka** [comment]
@bcedu fair enough. I found your app in the old appcenter and a new one thus leading me to the idea flatpak is the target. Anyway,I'll glad to help :)

**Comment by bcedu** [comment]
Yeah, the move to flatpak that elementary made is not something I would have chose, I personally don't like it, but I like elementary OS so I updated the app to publish in the new appcenter.

Thanks for the help!

**Pull request merged**
